### ISSUE TITLE
Feature Request: Login/logout event hook

### ISSUE THREAD

**Issue by schildbach** [lloesche/valheim-server-docker#254] opened 2021-03-21 16:53 UTC
I'm not sure if this is possible, but I'd like to have automated messages on our Matrix (or Discord) chat if a chracter logs into our server or logs out. Ideally, it would mention the character name on both events. Thus, I wonder if it is possible to add event hooks for that?

**Comment by vansoest** [comment] 2021-03-21 19:19
+1 I think that is a useful feature :)

**Comment by lloesche** [comment] 2021-03-21 20:59
On connect we're getting
```
03/12/2021 13:42:48: Got connection SteamID 76561197987220805
03/12/2021 13:42:49: Got handshake from client 76561197987220805
```

And related but not in any way identifiably connected
```
03/12/2021 13:43:17: Got character ZDOID from Luu : 1245460760:1
```

And on disconnect we get
```
03/12/2021 13:43:57: Closing socket 76561197987220805
```

So we could track the Steam ID for connecting/disconnecting. But there's no way to track the character name as none of the lines in the log connect the Steam ID with the character name or ID.

**Comment by schildbach** [comment] 2021-03-21 23:47
Printing/tracking the Steam ID is better than nothing. I'll try to ask the Valheim developers to add the necessary information to the log messages.

**Comment by lloesche** [comment] 2021-03-22 08:15
@schildbach well the thing is, the two connect lines are already printed before the password is checked. So you'd even see them for people connecting with the wrong password. Only the line `Got character ZDOID from` is a confirmed login.

So you can track SteamIDs who are "trying" to connect to your server. And you can track character names of successful logins. And then you can track SteamIDs that disconnect from your server. It's all a bit meh.

Anyhow, I've extended the existing log filter to allow event hooks. Meaning for any `VALHEIM_LOG_FILTER_` you define you can now specify a corresponding `ON_VALHEIM_LOG_FILTER_` containing the hook. Instead of removing those lines it will then pipe them to stdin of the `ON_` hook command.

Example (not for the faint of heart):
```
-e VALHEIM_LOG_FILTER_CONTAINS_Connected="Got character ZDOID from" \
-e ON_VALHEIM_LOG_FILTER_CONTAINS_Connected='{ read l; l=${l//*ZDOID from /}; l=${l// :*/}; msg="Player $l connected"; curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$msg\"}" "$DISCORD_WEBHOOK"; }'
```
resulting in
![image](https://user-images.githubusercontent.com/2124094/111959736-25bea500-8aef-11eb-9102-7dc2b8120e24.png)

Proper quoting is important here!

See also https://github.com/lloesche/valheim-server-docker#log-filter-event-hooks for all the details.

**Comment by schildbach** [comment] 2021-03-22 08:56
I've put this feature request on their tracker: https://valheimbugs.featureupvote.com/suggestions/172333/dedicated-server-log-lines-for-character-loginlogout

Feel free to upvote.

**Comment by lloesche** [comment] 2021-03-22 09:56
This feature is now implemented by https://github.com/lloesche/valheim-server-docker/commit/f7e207da8c4618d1ddd464322380fad9c35d9a34 and merged to `main`.

Let me know how it works for you. If no problems arise I will close this issue in a day or two.

**Comment by schildbach** [comment] 2021-03-22 17:55
The "Connected" hook works fine, thanks a lot for your quick solution! I've rewritten it a bit in order for using Matrix rather than Discord, but your "not for the faint of heart" remains. I wonder how resistent that is against shell escape attacks however (character names containing quotes and the like) .

**Comment by lloesche** [comment] 2021-03-22 20:27
> I wonder how resistent that is against shell escape attacks

I mean, you're getting the log line on stdin. Warts and all. Whatever you do with the data is up to you 🙂

In the example above if you were to inject some double quotes I guess you'd break the JSON and likely cause a JSON decoder error on Discords side.

**Comment by lloesche** [comment] 2021-03-22 20:41
@schildbach by the way would be great if you could contribute your Matrix hook script in `contrib/`. I'm sure it's gonna be useful for others as well.

**Comment by Genygo** [comment] 2021-03-22 21:04
So on any PlayerDeath there is a _Got character ZDOID from_ as well. Any ideas to ignore the hooks for this messages?

**Comment by lloesche** [comment] 2021-03-23 03:48
@Genygo not really. I fixed it very elegantly by changing the message from "Player connected" to "Player spawned" 😄 
Other than that you can just petition at Iron Gate to give us better log messages.

If you wanted to get experimental/unreliable you could try and match those `Got connection SteamID` and `Got character` together purely on a timing basis and then track `Closing socket` messages in a state machine and only send Discord messages whenever you get a `Got character` together with a new `Got connection SteamID`. But that is likely to break in situations where two or more players connect to the server around the same time.

**Comment by schildbach** [comment] 2021-03-23 10:03
> @schildbach by the way would be great if you could contribute your Matrix hook script in `contrib/`. I'm sure it's gonna be useful for others as well.

It's very similar to the Discord examples, so I've extended the README.md in a similar form. See https://github.com/lloesche/valheim-server-docker/pull/258.

**Comment by dipievil** [comment] 2021-03-23 15:26
Trying to use this to a Telegram Bot wich is much more easy. The only one thing I cant do is to parse this to the enviroment variable:

**Comment by fmdaboville** [comment] 2021-03-23 16:41
I'm facing issues using your example to perform the log of the player. I'm configuring it using an env_file, then I use it in the docker-compose file, like you show.

It logs to discord but without the player name, I see this in logs : 
` On log lines containing 'Got character ZDOID from' running '{ read l; l=""; l="${l// :*/}"; msg="Player $1 spawned into the world"; curl -sfSL -X POST -H ` (which end like this)
And then when player is connected : 
on discord : 'Player  spawned into the world'
on logs : `Running hook "{ read l; l=; l=${l// :*/}; msg=\"Player $1 spawned into the world **CumParty**\"; curl -sfSL -X POST -H \"Content-Type: application/json\" -d \"{\\\` (which end like this)

So in both logs, the part `l=${l//*ZDOID from /};` is missing but present in the env file. I can't figure out why, if you have any idea.

**Comment by dipievil** [comment] 2021-03-23 23:14
> It logs to discord but without the player name, I see this in logs :
> `On log lines containing 'Got character ZDOID from' running '{ read l; l=""; l="${l// :*/}"; msg="Player $1 spawned into the world"; curl -sfSL -X POST -H` (which end like this)

In wich logs you see this message?

**Comment by dipievil** [comment] 2021-03-23 23:29
I´m using the the Enviroments variables to send alerts to a Telegram bot. This is my configuration:

`      - TELEGRAM_BOT_TOKEN=MYBOTTOKEN
      - VALHEIM_LOG_FILTER_CONTAINS_Connected=Got character ZDOID from
      - ON_VALHEIM_LOG_FILTER_CONTAINS_Connected=curl -sfSL -X GET https://api.telegram.org/$TELEGRAM_BOT_TOKEN/sendMessage?chat_id=-MYCHATID&text=Um jogador conectou-se ao server!`

And theres no message in my chat. 

The only thing I got in the logs are:
`2021-03-23T23:22:25.479846477Z I0324 02:22:25.470949     159 main.go:66] Removing log lines containing 'Got character ZDOID from'`

It´s just removing the message?!

**Comment by DirtySoc** [comment] 2021-03-24 15:34
Hey all, great work on this. I just implemented this on my server, but I am getting duplicate messages because my server logs look like this:

```
Mar 24 11:29:02 /supervisord: valheim-server [Info   : Unity Log] 03/24/2021 11:29:02: Got character ZDOID from Thor : 1907444449:1
Mar 24 11:29:02 /supervisord: valheim-server 03/24/2021 11:29:02: Got character ZDOID from Thor : 1907444449:1
```

It looks like the search term to trigger the hook is being logged twice. Anyone else see this? Or have a suggestion to prevent the hook from firing twice? Would adding a `sleep 15` or something similar to the end of the hook script work?

**Comment by lloesche** [comment] 2021-03-25 06:38
@DirtySoc that's a ValheimPlus bug I reported here https://github.com/valheimPlus/ValheimPlus/issues/318
Although their response was "It's a BepInEx issue, go report it there". Which I couldn't be bothered to.

The issue has the `BepInEx.cfg` lines that changed with the 0.9.4 release. So if you have an old ValheimPlus version's `BepInEx.cfg` you won't see the issue. But if you only recently (in the last 2 weeks) installed it for the first time all the log lines are duplicated.

**Comment by lloesche** [comment] 2021-03-25 06:43
@fmdaboville

> `On log lines containing 'Got character ZDOID from' running '{ read l; l=""; l="${l// :*/}"; msg="Player $1 spawned into the world"; curl -sfSL -X POST -H` (which end like this)
> And then when player is connected :
> on discord : 'Player spawned into the world'
> on logs : `Running hook "{ read l; l=; l=${l// :*/}; msg=\"Player $1 spawned into the world\"; curl -sfSL -X POST -H \"Content-Type: application/json\" -d \"{\\\` (which end like this)

That looks correct. You are reading the player name into a variable `$l` and printing a variable `$1` which is likely empty?!

**Comment by lloesche** [comment] 2021-03-25 06:46
@dipievil the most likely cause is that you didn't update the container so you don't have the log event hooks.
Or your env variable config is off. But what you pasted looks correct. If you have the latest version of the container and the env variable config is correct the line `Removing ...` will turn into `On log lines ...`.

**Comment by corbin-lounsbury** [comment] 2021-03-25 19:24
Running into a snag trying to hook the connect event. I'm using the env file and this is how my hook is formatted:

`DISCORD_WEBHOOK=https://discord.com/api/webhooks/super_secret_webook

DISCORD_PRESHUTDOWN_MESSAGE=Server is SHUTTING DOWN!
PRE_SERVER_SHUTDOWN_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Hugin\",\"content\":\"$DISCORD_PRESHUTDOWN_MESSAGE\"}" "$DISCORD_WEBHOOK"

DISCORD_PRERESTART_MESSAGE=Server is RESTARTING!
PRE_RESTART_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Hugin\",\"content\":\"$DISCORD_PRERESTART_MESSAGE\"}" "$DISCORD_WEBHOOK"
DISCORD_POSTRESTART_MESSAGE=Server is RESTARTED!
POST_RESTART_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Hugin\",\"content\":\"$DISCORD_POSTRESTART_MESSAGE\"}" "$DISCORD_WEBHOOK"

DISCORD_POSTSTART_MESSAGE=Server is STARTED!
POST_START_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Hugin\",\"content\":\"$DISCORD_POSTSTART_MESSAGE\"}" "$DISCORD_WEBHOOK"

VALHEIM_LOG_FILTER_CONTAINS_Spawned="Got character ZDOID from"
ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned='{ read l; l=${l//*ZDOID from /}; l=${l// :*/}; msg="Player $l spawned into the world"; curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$msg\"}" "$DISCORD_WEBHOOK"; }'
`

The other hooks work just fine, but I'm not able to get the ON_VALHEIM_LOG one to work. Is there something I'm missing?

**Comment by lloesche** [comment] 2021-03-25 23:24
@corbin-lounsbury the entire command needs to be surrounded with `{}` otherwise `read` gets no data on `stdin`.
The format should be identical to the `-e` cli arg except for the `'` single quotes surrounding the command.

**Comment by corbin-lounsbury** [comment] 2021-03-26 00:04
> 
> 
> @corbin-lounsbury the entire command needs to be surrounded with `{}` otherwise `read` gets no data on `stdin`.
> The format should be identical to the `-e` cli arg except for the `'` single quotes surrounding the command.

Reformatted. Still not announcing server joins. Here's what I have now:

```
VALHEIM_LOG_FILTER_CONTAINS_Spawned="Got character ZDOID from"
ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned={ read l; l=${l//*ZDOID from /}; l=${l// :*/}; msg="Player $l spawned into the world"; curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$msg\"}" "$DISCORD_WEBHOOK"; }
```

**Comment by lloesche** [comment] 2021-03-26 09:55
@corbin-lounsbury check [the README](https://github.com/lloesche/valheim-server-docker#inside-an-env_file) example. You must not have any quotes around your values in an env file. They become part of the value. With your current config the log filter is looking for the string `"Got character ZDOID from"` including the double quotes surrounding it. It's just one of those Docker quirks.

**Comment by viab23** [comment] 2021-03-26 09:55
> 
> 
> > @corbin-lounsbury the entire command needs to be surrounded with `{}` otherwise `read` gets no data on `stdin`.
> > The format should be identical to the `-e` cli arg except for the `'` single quotes surrounding the command.
> 
> Reformatted. Still not announcing server joins. Here's what I have now:
> 
> ```
> VALHEIM_LOG_FILTER_CONTAINS_Spawned="Got character ZDOID from"
> ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned={ read l; l=${l//*ZDOID from /}; l=${l// :*/}; msg="Player $l spawned into the world"; curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$msg\"}" "$DISCORD_WEBHOOK"; }
> ```

You have to delete the quotes in `VALHEIM_LOG_FILTER_CONTAINS_Spawned="Got character ZDOID from"` - then it should work.

**Comment by schildbach** [comment] 2021-03-26 10:07
I wonder if we should encourage all users to use the `valheim.env` file approach when it comes to hooks and log filters. Env files have the advantage of *not* requiring another level of character escaping. And it can be used from Docker (via `--env-file` option) and Docker-Compose (via `env_file` in docker-compose.yaml) alike.

**Comment by Jansuun** [comment] 2021-03-26 19:53
I have the same issue that player names aren't reported in discord when the following lines are added to the env_file:

`VALHEIM_LOG_FILTER_CONTAINS_Spawned="Got character ZDOID from"
ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned={ read l; l=${l//*ZDOID from /}; l=${l// :*/}; msg="Player $l spawned into the world"; curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$msg\"}" "$DISCORD_WEBHOOK"; }`

It seems that the `l=${l//*ZDOID from /}` isn't fully taken over when running the hook which is strange....

`Mar 26 20:45:58 /supervisord: valheim-server I0326 20:45:58.086873     115 main.go:220] Running hook "{ read l; l=; l=${l// :*/}; msg=\"Player $l spawned into the world\"; curl -sfSL -X POST -H \"Content-Type: application/json\" -d \"{\\\"usernam`

**Comment by corbin-lounsbury** [comment] 2021-03-27 00:41
@viab23 @lloesche Thank you both. I had originally overlooked that. That hook worked.

**Comment by lloesche** [comment] 2021-03-27 10:57
@Jansuun that's just busybox's syslogd truncating log lines longer than 255 characters.
I can push a PR that recompiles busybox with a larger read buffer size.

**Comment by lloesche** [comment] 2021-03-27 14:45
@Jansuun just merged https://github.com/lloesche/valheim-server-docker/commit/182fd562331b542dc63133ce8e94038ac41dcb54 which increases the read buffer from 256 to 2048 bytes. When you pull the latest image your log lines will no longer be truncated.

**Comment by Jansuun** [comment] 2021-03-29 15:22
Still got the same situation where the first trim is removed i.e. ``` l=${l//*ZDOID from /}; ``` ends up as ```  l=; ```

```
valheim_1  | Mar 29 17:12:34 /supervisord: valheim-server I0329 17:12:34.915755     137 main.go:220] Running hook "{ read l; l=; l=${l// :*/}; msg=\"Player $l spawned into the world\"; curl -sfSL -X POST -H \"Content-Type: application/json\" -d \"{\\\"username\\\":\\\"Valheim\\\",\\\"content\\\":\\\"$msg\\\"}\" \"$DISCORD_WEBHOOK\"; }" for "03/29/2021 17:12:34: Got character ZDOID from Pannekoek : 1530332139:8"
```

For now i have workaround which works for me:

```
ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned={ read l; msg=${l:46}; msg=${msg/ :*/ has come online}; curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$msg\"}" "$DISCORD_WEBHOOK"; }
```
```
valheim_1  | Mar 29 17:20:07 /supervisord: valheim-server I0329 17:20:07.141494     137 main.go:220] Running hook "{ read l; l=${l:46}; l=${l// :*/}; msg=\"Player $l spawned into the world\"; curl -sfSL -X POST -H \"Content-Type: application/json\" -d \"{\\\"username\\\":\\\"Valheim\\\",\\\"content\\\":\\\"$msg\\\"}\" \"$DISCORD_WEBHOOK\"; }" for "03/29/2021 17:20:07: Got character ZDOID from Pannekoek : 1354471836:8"
```

![image](https://user-images.githubusercontent.com/6660849/112859488-2fc64200-90b3-11eb-8afd-6168693405f4.png)

**Closed** 2021-04-01 16:20 UTC
Labels: enhancement

**Comment by dipievil** [comment] 2021-04-02 12:34
> @dipievil the most likely cause is that you didn't update the container so you don't have the log event hooks feature.
> Or your env variable config is off. But what you pasted looks correct. If you have the latest version of the container and the env variable config is correct the line `Removing ...` will turn into `On log lines ...`.

I have the latest version of the container:

[https://i.imgur.com/Y5wBcbh.png](https://i.imgur.com/Y5wBcbh.png)
