### ISSUE TITLE
Server not showing up on browse in game and Steam but can access from IP

### ISSUE THREAD

**Issue by alvarofvr** [lloesche/valheim-server-docker#75] opened 2021-02-21 13:45 UTC
Hi, I just notice that I can access in the server using IP address from game (Join with IP option), but the server not showing on the list in game browse and Steam server list. Why?

The PUBLIC option is set to default, so 1.

**Comment by Hydeo** [comment] 2021-02-21 15:30
Did you open the 2457 port ? 
I believe this is the port used to find your server on Steam Browser, 2456 will be the one you use to connect to it.

**Comment by joshaspinall** [comment] 2021-02-21 15:43
2458 is also in the instructions for the Container.  I am unsure as to the function of 2458 but am sure someone will be able to clarify.

**Comment by alexdie** [comment] 2021-02-21 21:06
It seems that the public server list has an upper limit and only the first ~5000 are currently showing up. 
My server showed up until it switched IPs. Everything else was completely identical.

**Comment by lloesche** [comment] 2021-02-22 00:54
Duplicate of https://github.com/lloesche/valheim-server-docker/discussions/73
Ever since the game got popular new servers are rarely shown in-game. It used to be that servers would show up in-game but for about the past two weeks the game still only shows up to 5k servers while the number of concurrent players is around half a million by now.

**Closed by lloesche** 2021-02-22 00:54 UTC
Labels: duplicate, question
