### ISSUE TITLE
[BUG] server restarting by itself

### ISSUE THREAD

**Issue by yasumitsuru** [lloesche/valheim-server-docker#543] opened 2022-12-15 22:03 UTC
OS: Linux server
Valheim game version: 0.212.7
V+ Mod Version: 0.9.9.11
describe the bug
From now on the Valheim-server restarts internally in Docker both KVM Ubuntu 20.04 x64 and Docker health are ok the problem is found internally.
OS: Linux server
Valheim game version: 0.212.7
V+ Mod Version: 0.9.9.11
describe the bug
From now on the Valheim-server restarts internally in Docker both KVM Ubuntu 20.04 x64 and Docker health are ok the problem is found internally.

[_valheim_logs.txt](https://github.com/lloesche/valheim-server-docker/files/10241014/_valheim_logs.txt)
[valheim_plus.txt](https://github.com/lloesche/valheim-server-docker/files/10241015/valheim_plus.txt)

I already removed all mods and the problem persists
I currently only have the Advize_PlantEverything mod active on the server side.

"Translated by google translator"

**Comment by ryanturcotte** [comment] 2022-12-17 23:30
I'm having a similar problem with a docker instance on an amazon ec2. No mods.
[valheim-server-log-12-17-22.txt](https://github.com/lloesche/valheim-server-docker/files/10252910/valheim-server-log-12-17-22.txt)

**Comment by mzrimsek** [comment] 2022-12-18 04:08
By default the server restarts every day at 5am. You need to overwrite the environment variable for the container to disable the restarts.

**Comment by ryanturcotte** [comment] 2022-12-18 17:53
> By default the server restarts every day at 5am. You need to overwrite the environment variable for the container to disable the restarts.

That could be the OP's problem. I'll make a new issue if mine keeps persisting. Haven't been using the server much.

**Comment by yasumitsuru** [comment] 2022-12-19 01:52
> By default the server restarts every day at 5am. You need to overwrite the environment variable for the container to disable the restarts.

Thanks for listening,

what I noticed was that every 1h the world restarted when the system backed up.

my way out was to eliminate kvm ubuntu and run debian 11 I stopped having this problem.

before I had deleted 100% of the docker plus the image and I still had the problem.

I restored my world in debian 11 docker and for now it's ok. I'll keep monitoring to see if the problem comes back.

Thank you all.

"Translated by google translator"

**Comment by lloesche** [comment] 2022-12-22 01:54
The most common reason for unexpected restarts is not enough RAM. Then every time the updater runs, the Kernel's OOM killer will remove the process that currently consumes the most RAM (i.e. valheim-server itself).

If the issue is happening on older Linux Kernels check if the `:debian10` version of the container works. We also just merged a PR that should fix any 32bit library issues in the debian11 container.

**Closed by lloesche** 2022-12-22 01:54 UTC
