### ISSUE TITLE
valheim_1  | standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by martins8977** [lloesche/valheim-server-docker#220] opened 2021-03-13 17:01 UTC
When I run the  docker-compose up, an error was shown: valheim_1  | standard_init_linux.go:219: exec user process caused: exec format error.

I'm using a raspberry 4

**Comment by lloesche** [comment] 2021-03-13 18:04
Duplicate of https://github.com/lloesche/valheim-server-docker/issues/46

**Closed by lloesche** 2021-03-13 18:04 UTC
Labels: duplicate
