### ISSUE TITLE
World not saved on shutdown

### ISSUE THREAD

**Issue by wedol** [lloesche/valheim-server-docker#13] opened 2021-02-11 09:44 UTC
When restarting/shutting down the container, valheim server is terminated and not gracefully closed -> world is not saved.
Log:
> Shutting down Valheim Server with PID 78
Waiting for Valheim Server shutdown
/usr/local/bin/valheim-server: line 31: /opt/valheim/server_exit.drp: Permission denied
Waiting for Valheim Server shutdown
Waiting for Valheim Server shutdown
2021-02-11 09:37:47,845 INFO waiting for valheim-server to die
Waiting for Valheim Server shutdown
Waiting for Valheim Server shutdown
2021-02-11 09:37:50,850 INFO waiting for valheim-server to die
Waiting for Valheim Server shutdown
Waiting for Valheim Server shutdown
Waiting for Valheim Server shutdown
2021-02-11 09:37:53,854 INFO waiting for valheim-server to die
Waiting for Valheim Server shutdown

After this long waiting, container is terminated.

**Comment by lloesche** [comment] 2021-02-11 11:13
Can you check if you are running the latest version of the container image?
The line
```
/usr/local/bin/valheim-server: line 31: /opt/valheim/server_exit.drp: Permission denied
```
means that the `steam` user has no write permissions to `/opt/valheim`. This issue was fixed a bit ago in https://github.com/lloesche/valheim-server-docker/commit/aa7eed85e8ca444ab6f30cf3a627500a7bfdf39a

So usually what should happen is, the valheim-server script receives a `SIGTERM` and creates `/opt/valheim/server_exit.drp` which makes the server process shutdown gracefully and save the world.

It's only if this process takes more than 1 minute that supervisord will run into a timeout and shut down the server process itself.

**Comment by Kuschluk** [comment] 2021-02-11 12:38
Hi lloesche,
same issue here created got the package over synology gui as "latest" just an hour ago.

**/usr/local/bin/valheim-server: line 31: /opt/valheim/server_exit.drp: Permission denied**

I now exported my container to do the script changes manuals :/ 

not really cool 167MB -unzip> 1Gb ---> 99% unchanged --> gz tar --> import :/ (is there a smarter way to do so ?) 

Running on a Synology, the guys who expect a disconnect after 1st join should wait just a minute then everything is fine. But I tried if the map will save when I stop the container and came to the issue mentioned above.

BR

**Comment by Kuschluk** [comment] 2021-02-11 13:02
Anyway great Work for FREE 😀

**Comment by wedol** [comment] 2021-02-11 13:33
> Can you check if you are running the latest version of the container image?

Yes, latest version.

**Comment by LHolst** [comment] 2021-02-11 13:40
getting the same `/usr/local/bin/valheim-server: line 31: /opt/valheim/server_exit.drp: Permission denied` 

and an additionall world***.zip backup file, but owned by `root:root` 

could it be an issue that the valheim server runs as `steam` but the backup as `root`  user?

**Comment by LHolst** [comment] 2021-02-11 13:43
`/opt/valheim` has `steam` user permission, but all files under `/opt/valheim`  are owned by `root `, including a `server_exit.drp` file

**Comment by LHolst** [comment] 2021-02-11 13:58
@wedol
> And i noticed this in changelog for valheim:
> 
> > Dedicated server ugly file-flag shutdown system removed (Use CTRL-C or SIGINT instead)

seems like the `server_exit.drp` is obsolete

**Comment by Kuschluk** [comment] 2021-02-11 14:04
> @wedol
> 
> > And i noticed this in changelog for valheim:
> > > Dedicated server ugly file-flag shutdown system removed (Use CTRL-C or SIGINT instead)
> 
> seems like the `server_exit.drp` is obsolete

But where to Do?  I hosted my Server on my local Windows mach in last weeks. Everytime I closed it i did via ctr +c. When I go to my synology Docker terminal Window and push ctr +c I End up with the issue and an unsaved world

**Comment by Wimsen** [comment] 2021-02-11 15:37
I just tested the fix from #14 - it seems to gracefully shut down now and save the world state as expected 👏

**Comment by TopCheddar27** [comment] 2021-02-11 15:40
@lloesche 
I see you committed a fix for this. Is there any best practices to shutdown the current process before upgrading the container? Should I just get a interactive shell and send a kill manually? Then pull the latest container? Should I expect the save to be corrupted? It's not a huge issue because of your great integration of backup schedules.

**Comment by lloesche** [comment] 2021-02-11 16:16
@TopCheddar27 yes so to be super safe you can get a shell and `echo 1 > /opt/valheim/server_exit.drp`. Then if the server process is still in the `ps ax` list it means you have the new version of the server already and can send a `kill -INT <pid>` to the server pid. The server is the process called `valheim_server.x86_64` not `valheim-server`.

**Comment by lloesche** [comment] 2021-02-11 16:20
@wedol just confirmed. This was caused by an update of the valheim_server and the way they shut down the server. In the past you would have to create a file `server_exit.drp`. Now you have to send a SIGINT to shut it down. Unfortunately they didn't make it backwards compatible so that the old way still worked in addition to the new way essentially breaking all existing shutdown scripts. Which I guess is fair considering they are in early access, but still would have been nice.

Anyhow thanks to @LHolst s PR the server now shuts down cleanly again.

**Closed by lloesche** 2021-02-11 16:20 UTC
Labels: bug

**Comment by Kuschluk** [comment] 2021-02-11 16:52
Works now for me well! Thanks a lot :)
