### ISSUE TITLE
Client keeps crashing every ~20 minutes

### ISSUE THREAD

**Issue by Flashbin** [lloesche/valheim-server-docker#314] opened 2021-04-11 17:28 UTC
Hi,

I've set up a Valheim Server with this docker image today and copied over my local world, on which I've played with a friend. Now, his game crashes every 20 minutes or so.
Considering that it's his game crashing and not the server I would think that it's got nothing to do with the server. But when I was hosting the server locally within the game, there were no crashes.
My game is still fine, I connect to the server locally since it's in my LAN, he connect from outside (ports 2456-2458 are forwarded).
Here are the logs after his game crashed: [valheim.log](https://github.com/lloesche/valheim-server-docker/files/6292351/valheim.log)

Would really appreciate if someone could help, since every time his game crashes, some progress gets lost (he always spawns back at the spawnpoint, items sometimes disappear, some duplicate etc.)

Thanks!

**Comment by lloesche** [comment] 2021-04-12 01:49
Your setup looks completely fine. The only thing I'd be wary of is the assigned storage quota. You got 1.5 GB left and when a server update comes in it'll temporarily require 1.1 GB extra. That's cutting it pretty close. Just to be on the safe side I'd provision an extra 4 GB to the container.

The only thing I see somewhat in the proximity of their crash, which you've probably seen too, is the Dungeon load. Did their client crash when they entered the Dungeon? Or did you enter the Dungeon and their client crashed?

Other than that, does either of you have any mods installed that might conflict with any mods or missing mods on the server? Or is both the server and all clients plain vanilla Valheim?

**Comment by Flashbin** [comment] 2021-04-12 13:28
Thanks for the hint, I'll add more storage to the server.

The crash happened independently of anyone entering a dungeon, we've entered a few and his game crashed like 5 to 10 minutes after. But it had also crashed with no dungeons entered previously, so that can't be the issue. The crashes happen seemingly random, sometimes he's just running around, sometimes he's standing in the base or fighting monsters.

Both the server and clients are plain vanilla. I'll see if I can get another friend to test the server from outside and see if their game crashes too.

Is `docker logs` the only place where the valhalle server writes logs or are there other places to monitor?

Thanks for the help!

**Comment by lloesche** [comment] 2021-04-12 19:49
Docker logs is the only place unless you configure an external syslog server using the `SYSLOG_REMOTE_HOST` option.

**Comment by Dani20000** [comment] 2021-04-13 15:30
I might have the same problem... but my server isn't vanilla, it has only one mod called ServerSideMap. My friend sometimes randomly logout (no dungeons at all, we just started, just walking or fighting), before i saw this issue i thinked that he was having internet connection problems. But he says he never had any before. Do you want me to post the logs of when the crash happens? But where can i find yesterday logs? Docker only shows last ~6 hours. Or maybe you want the player log (my friend's one player.log)? Thank you

**Comment by lloesche** [comment] 2021-04-14 08:36
@Dani20000 sure attach the server log here. Docker should have the complete log from start to now. When I `docker logs valheim-server > valheim.log` I get several weeks worth of logs. If that's not the case on your system maybe there's some docker daemon logging setting that's truncating the logs? No idea.

Although I'm guessing if the container doesn't crash (i.e. if he gets disconnected but you don't) then it's a client issue that we can't do much about and the Steam community is likely the better place to debug the issue.

**Comment by Flashbin** [comment] 2021-04-14 09:13
@Dani20000 Did you start fresh with a generated world from the server or did you copy a world over from your PC?

**Comment by Dani20000** [comment] 2021-04-16 21:48
> @Dani20000 sure attach the server log here. Docker should have the complete log from start to now. When I `docker logs valheim-server > valheim.log` I get several weeks worth of logs. If that's not the case on your system maybe there's some docker daemon logging setting that's truncating the logs? No idea.
> 
> Although I'm guessing if the container doesn't crash (i.e. if he gets disconnected but you don't) then it's a client issue that we can't do much about and the Steam community is likely the better place to debug the issue.

By chance when i delete the container (but not the volumes nor the image) also the logs get deleted? Because i updated some env variables, and therefore i had to delete the container.

**Comment by Dani20000** [comment] 2021-04-16 21:49
> @Dani20000 Did you start fresh with a generated world from the server or did you copy a world over from your PC?

I copied a world from my PC

**Comment by Flashbin** [comment] 2021-04-19 19:40
Just tested copying the world from the server to my local PC and hosting it from there, his game still keeps crashing. So the issue is not with the server, but I'm thinking either with the world if it somehow got corrupted or if his game or his character got corrupted. I just find it very weird that it first occured when switching to the server.

**Comment by lloesche** [comment] 2021-05-17 15:47
Closing as the issue is server/client related and there's nothing we can do inside this container.

**Closed by lloesche** 2021-05-17 15:47 UTC
Labels: question
